name: pipeline_test

on:
  release:
    types: [created]
env:
  EXCEL_SHEET: "Sheet1"
  INPUT_FILE: "file:/home/runner/work/FillDataInSpreadSheet/src/test/resources/input.xlsx"
  NUM_ROWS: "10"
  OUTPUT_FILE: "file:/home/runner/work/FillDataInSpreadSheet/src/test/resources/output.xlsx"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
